// User Top Timepiece V1 — top-level multi-mode wrapper.
//
// Modes are selected by SW[1:0]:
//   00 = Watch (clock, default)
//   01 = Stopwatch
//   10 = Sequencer (with audio)
//   11 = Timer
//
// brightness_enable output tells the surrounding brightness wrapper
// whether SW[9:8] should control display dimming. It's only asserted in
// modes that don't need SW[9:8] for other purposes (watch + stopwatch).
//
// Audio is generated by the sequencer; in all other modes the audio
// output is muted (zeros) but still handshakes with audio_core so the
// codec stays happy.

`timescale 1ns / 1ps

module user_top_timepiece_v1 #(
    parameter int CYCLES_PER_SECOND = 50_000_000
) (
    input logic       clk,
    input logic [3:0] button,
    input logic [9:0] sw,

    output logic [9:0] led,
    output logic [6:0] hours_disp,
    output logic [6:0] minutes_disp,
    output logic [6:0] seconds_disp,
    output logic       blank_hours,
    output logic       blank_minutes,
    output logic       blank_seconds,

    // High when brightness control should apply (clock/stopwatch modes).
    // Low for sequencer/timer modes that use SW[9:8] for other purposes.
    output logic brightness_enable,

    // Audio sink interface (forwarded to/from audio_core)
    input  logic        left_ready,
    input  logic        right_ready,
    output logic [31:0] left_data,
    output logic [31:0] right_data,
    output logic        left_valid,
    output logic        right_valid
);

  typedef struct packed {
    logic [3:0] button;
    logic [9:0] sw;
  } ui_in_t;

  typedef struct packed {
    logic [9:0] led;
    logic [6:0] hours_disp;
    logic [6:0] minutes_disp;
    logic [6:0] seconds_disp;
    logic       blank_hours;
    logic       blank_minutes;
    logic       blank_seconds;
  } ui_out_t;

  ui_in_t watch_in, timer_in, sw_in, seq_in;
  ui_out_t watch_out, timer_out, sw_out, seq_out;

  // -------------------------------------------------------------------------
  // Watch (clock) mode
  // -------------------------------------------------------------------------
  user_top_watch_v4 #(
      .CYCLES_PER_SECOND(CYCLES_PER_SECOND)
  ) u_user_top_watch_v4 (
      .clk(clk),
      .button(watch_in.button),
      .sw(watch_in.sw),
      .led(watch_out.led),
      .hours_disp(watch_out.hours_disp),
      .minutes_disp(watch_out.minutes_disp),
      .seconds_disp(watch_out.seconds_disp),
      .blank_hours(watch_out.blank_hours),
      .blank_minutes(watch_out.blank_minutes),
      .blank_seconds(watch_out.blank_seconds)
  );

  // -------------------------------------------------------------------------
  // Timer mode
  // -------------------------------------------------------------------------
  user_top_timer_v1 #(
      .CYCLES_PER_SECOND(CYCLES_PER_SECOND)
  ) u_user_top_timer_v1 (
      .clk(clk),
      .button(timer_in.button),
      .sw(timer_in.sw),
      .led(timer_out.led),
      .hours_disp(timer_out.hours_disp),
      .minutes_disp(timer_out.minutes_disp),
      .seconds_disp(timer_out.seconds_disp),
      .blank_hours(timer_out.blank_hours),
      .blank_minutes(timer_out.blank_minutes),
      .blank_seconds(timer_out.blank_seconds)
  );

  // -------------------------------------------------------------------------
  // Stopwatch mode
  // -------------------------------------------------------------------------
  user_top_stopwatch_v1 #(
      .CYCLES_PER_SECOND(CYCLES_PER_SECOND)
  ) u_user_top_stopwatch_v1 (
      .clk(clk),
      .button(sw_in.button),
      .sw(sw_in.sw),
      .led(sw_out.led),
      .hours_disp(sw_out.hours_disp),
      .minutes_disp(sw_out.minutes_disp),
      .seconds_disp(sw_out.seconds_disp),
      .blank_hours(sw_out.blank_hours),
      .blank_minutes(sw_out.blank_minutes),
      .blank_seconds(sw_out.blank_seconds)
  );

  // -------------------------------------------------------------------------
  // Sequencer mode (with audio output)
  // -------------------------------------------------------------------------
  logic [31:0] seq_left_data;
  logic [31:0] seq_right_data;
  logic        seq_left_valid;
  logic        seq_right_valid;

  user_top_sequencer_v1 #(
      .CYCLES_PER_SECOND(CYCLES_PER_SECOND)
  ) u_user_top_sequencer_v1 (
      .clk(clk),
      .button(seq_in.button),
      .sw(seq_in.sw),
      .led(seq_out.led),
      .hours_disp(seq_out.hours_disp),
      .minutes_disp(seq_out.minutes_disp),
      .seconds_disp(seq_out.seconds_disp),
      .blank_hours(seq_out.blank_hours),
      .blank_minutes(seq_out.blank_minutes),
      .blank_seconds(seq_out.blank_seconds),
      .left_ready(left_ready),
      .right_ready(right_ready),
      .left_data(seq_left_data),
      .right_data(seq_right_data),
      .left_valid(seq_left_valid),
      .right_valid(seq_right_valid)
  );

  // -------------------------------------------------------------------------
  // Multiplexers
  // -------------------------------------------------------------------------
  ui_in_t ui_top_in;
  assign ui_top_in.sw     = sw;
  assign ui_top_in.button = button;

  ui_in_t ui_top_in_no_buttons;
  assign ui_top_in_no_buttons.sw     = sw;
  assign ui_top_in_no_buttons.button = '0;

  ui_out_t ui_top_out;
  assign led           = ui_top_out.led;
  assign hours_disp    = ui_top_out.hours_disp;
  assign minutes_disp  = ui_top_out.minutes_disp;
  assign seconds_disp  = ui_top_out.seconds_disp;
  assign blank_hours   = ui_top_out.blank_hours;
  assign blank_minutes = ui_top_out.blank_minutes;
  assign blank_seconds = ui_top_out.blank_seconds;

  logic [1:0] mode_sel;
  assign mode_sel = sw[1:0];

  // Brightness control enabled only in clock (00) and stopwatch (01) modes
  always_comb begin
    case (mode_sel)
      2'b00:   brightness_enable = 1'b1;  // Clock
      2'b01:   brightness_enable = 1'b1;  // Stopwatch
      default: brightness_enable = 1'b0;  // Sequencer (10) or Timer (11)
    endcase
  end

  always_comb begin
    sw_in    = ui_top_in_no_buttons;
    timer_in = ui_top_in_no_buttons;
    watch_in = ui_top_in_no_buttons;
    seq_in   = ui_top_in_no_buttons;
    case (mode_sel)
      // Stopwatch
      2'b01: begin
        sw_in      = ui_top_in;
        ui_top_out = sw_out;
      end
      // Sequencer
      2'b10: begin
        seq_in     = ui_top_in;
        ui_top_out = seq_out;
      end
      // Timer
      2'b11: begin
        timer_in   = ui_top_in;
        ui_top_out = timer_out;
      end
      // Watch (default)
      default: begin
        watch_in   = ui_top_in;
        ui_top_out = watch_out;
      end
    endcase
  end

  // Audio routing: pass sequencer audio when in sequencer mode, else silent.
  always_comb begin
    if (mode_sel == 2'b10) begin
      left_data   = seq_left_data;
      right_data  = seq_right_data;
      left_valid  = seq_left_valid;
      right_valid = seq_right_valid;
    end else begin
      left_data   = 32'h00000000;
      right_data  = 32'h00000000;
      left_valid  = left_ready;
      right_valid = right_ready;
    end
  end

endmodule
